### ISSUE TITLE
Can I Change State Fill Color Dynamically?

### ISSUE THREAD

**Issue by medined** [NewSignature/us-map#3]
You've made a very nice plugin.. It does exactly what I am looking for. However, I have not found a way to change the fill color of a state dynamically. It must be possible because the mousein and mouseout events do it. Thanks in advance.

**Comment by medined** [comment]
After several hours of code tracing, I found out that just one line of javascript needs to be added to your plugin. In jquery.usmap.js add "this.stateShapes[state].node.setAttribute("id", state);" after line 270. Then you can easily change the state color using $('#CA').css('fill','white');

**Comment by awolfey** [comment]
@medined I'm using your fix, but it seems to disable future hover effects on any state where the fill is set. Did you find a better solution? Thanks

**Comment by medined** [comment]
I'm sorry but I did not need to look past the workaround that I posted.

**Comment by econbassman** [comment]
@medined Could you post an example of where to include the "$('#CA').css('fill','white');" bit of code?  I made the mod to the js file, but can't get the fill color to work.  I'm attempting to loop over a list of states to give them a certain color. Thanks in advance.

**Comment by medined** [comment]
I haven't looked at this project recently and I can't remember any details.
Sorry.

**Comment by awolfey** [comment]
@econbassman Maybe this will help:

``` javascript
 function setStateColors(list) {
    list = (typeof list === "undefined") ? $('.view-resource-list .views-row') : list;

    for (var key in usStates) {
      if (jQuery.inArray(key, states) !== -1 && list.filter('.' + key).length > 0) {
        $('#' + key).css('fill', '#F8C71B');
      }
      else if (list.filter('.' + key).length > 0) {
        $('#' + key).css('fill', '#b0b0b0');
      }
      else {
        $('#' + key).css('fill', '#e0e0e0');

      }

    }
  }
```

**Comment by dfstewart3** [comment]
This works like a charm!  Thank you!

**Comment by manvindersingh12** [comment]
I was using this map.  But I am not able to get the state name 2 digit lables to become visible.  Is there any flag that we can setup for the state name to appear?
