### ISSUE TITLE
Can't Get Table to Work At All

### ISSUE THREAD

**Issue by eweisbrot** [NewSignature/us-map#40]
Hello,

To preface this, I am a complete novice to jQuery. I've followed the directions on the website here http://newsignature.github.io/us-map/, but I can't seem to get the map working at all. I'm just trying to get the map to display towards the bottom of the page with each state having a clickable links.

Please see my webpage here: http://199.119.123.135/surety-bonds/commercial-bonds/auto_dealer_bond_map.htm

I also tried searching for solutions elsewhere online, but can't figure it out. Any help is much appreciated. Thanks!

**Comment by kcaran** [comment]
You need to have jquery.min.js defined in your html before the plugins.

Normally, it's better performance if all of your scripts are at the bottom. You have so many scripts that it might not be feasible.

**Comment by eweisbrot** [comment]
Hello,

Thanks for the response. I tried placing the US map plugins after the jquery.min.js, but it's still not working. Am I understanding correctly?

**Comment by eweisbrot** [comment]
I finally got the map to display! All I want to do is have each state link to various pages in our website, but I can't figure out how to do this. Any advice?
