### ISSUE TITLE
Change hover color of New England and small state label boxes?

### ISSUE THREAD

**Issue by kjrhody** [NewSignature/us-map#63]
I noticed that changing the `stateHoverStyles` property will change the color of the actual state but not the color of the label box for the smaller northeastern states. Even specifying for the state (`stateSpecificHoverStyles`) does not work. Does anyone have suggestions for fixing this?

**Comment by kcaran** [comment]
I have a pull request to fix this:

https://github.com/kcaran/us-map

Example here:
http://www.kcaran.com/us-map-example/

**Comment by kjrhody** [comment]
Thank you! The line that fixed it was by setting the `fill` property of `labelBackingHoverStyles` to the same color as `stateHoverStyles`.
